services:
  api:
    build: .
    container_name: disaster-relief-api

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

    volumes:
      - ./model_weights:/app/model_weights

  postgres:
    image: postgres:17
    container_name: disaster-relief-optimizer-db

    restart: always

    environment:
      POSTGRES_USER: apyotDev
      POSTGRES_PASSWORD: apyotyyDev
      POSTGRES_DB: disaster_relief_optimizer

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
